### ISSUE TITLE
[test] System Tests for C Interface

### ISSUE THREAD

**Issue by ppenna** [demikernel/demikernel#131]
Context
---------

Our C regression suite currently misses system tests.

Due to this we recently missed a critical bug to be introduced in the `unstable` branch https://github.com/demikernel/demikernel/issues/130.

Proposed Solution
---------------------

Provide C system tests for the following Rust tests:

- [x] `udp_push_pop` #133 
- [X] `udp_ping_pong` #150
- [x] `tcp_push_pop` #139 
- [x] `tcp_ping_pong` #151
