### ISSUE TITLE
[test] Remove `unwrap()`, `expect()` and `panic()` from All Tests

### ISSUE THREAD

**Issue by ppenna** [demikernel/demikernel#207]
Description
========

In some tests we rely on `unwrap()`, `expect()` and `panic()` to assert for expected successful operations. While this is valid, it make it harder to find out where in the source code we failed. For this reason, we should use `assert!` macro family instead.

- [ ] Unit Tests: src/
- [ ] Integration: tests/rust Tests PR #637 
- [ ] examples/pipe-open PR #639 
- [ ] examples/rust/pipe-*
- [ ] examples/rust/tcp-*
- [ ] examples/rust/udp-*
- [ ] examples/tcp-close PR #641 
- [ ] examples/tcp-echo PR #643
